In [1]:
import numpy as np

In [4]:
X=np.array([[0,0],[0,1],[1,0],[1,1]])
Y=np.array([[0,0,0,1]]).T
print(X.shape)
print(Y.shape)

(4, 2)
(4, 1)


In [23]:
def sig(z):
    return (1/(1+np.exp(-z)))

In [24]:
#no hidden layer weights
weights= 2*np.random.random((2,1))-1
bias=2*np.random.random(1)-1
weights , bias

(array([[ 0.71213427],
        [-0.39393885]]),
 array([-0.60676882]))

In [25]:
#forward propagation without any hidden layer
output0=X
output=sig(np.dot(output0, weights) + bias)
output

array([[0.35279663],
       [0.26880231],
       [0.52631702],
       [0.42835316]])

In [26]:
wh = 2 * np.random.random((2,2))-1 #hidden weights
bh = 2 * np.random.random((1,2))-1 #hiddent bias
wo= 2 * np.random.random((2,1))-1 #output weights
bo= 2 * np.random.random((1,1))-1 #output bias

In [27]:
output0=X
outputHidden=sig(np.dot(output0, wh) + bh)
output=sig(np.dot(outputHidden, wo) + bo)
output

array([[0.62162472],
       [0.61914597],
       [0.62098034],
       [0.61866359]])