In [3]:
import numpy as np

In [4]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [5]:
np.array([1,2,3],dtype=bool)

array([ True,  True,  True])

In [6]:
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [7]:
np.array([1,2,.23])

array([1.  , 2.  , 0.23])

### arange()

In [8]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np.arange(1,11,3)

array([ 1,  4,  7, 10])

### reshape()

In [10]:
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

### np.ones() and np.zeros()

np.ones((3,4))  #default float

In [13]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### np.random.random()

In [16]:
np.random.random((3,4))  #generates random values b/w 0 and 1

array([[0.54136844, 0.73787854, 0.88563441, 0.3501071 ],
       [0.40180326, 0.88335429, 0.40940653, 0.34632792],
       [0.32101515, 0.06150328, 0.03388276, 0.16124885]])

### linspace()  -> linear space

In [18]:
np.linspace(-10,10,10)  #equidistant adjacent elements b/w -10 and 10

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [21]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Array Attributes

In [46]:
a1=np.arange(10, dtype=np.int32)
print(a1)

[0 1 2 3 4 5 6 7 8 9]


In [33]:
a2=np.arange(12,dtype=float).reshape(3,4)
print(a2)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [54]:
a3=np.arange(8).reshape(2,2,2)
print(a3)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [37]:
#np.ndim
a1.ndim, a2.ndim

(1, 2)

In [39]:
#np.shape()
np.shape(a1),np.shape(a3)

((10,), (2, 2, 2))

In [42]:
a3.size #number of elements

8

In [47]:
a1.itemsize #gives byte of element

4

In [48]:
a2.itemsize #gives byte of element

8

In [49]:
a3.itemsize #gives byte of element

8

In [52]:
#dtype
a1.dtype

dtype('int32')

In [53]:
a2.dtype

dtype('float64')

In [55]:
a3.dtype

dtype('int64')

## Changing Datatype

In [56]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

## Array Operations

In [61]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
a1,a2

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]))

### scalar operations

In [65]:
#arithmetic(+,-,/,*,**)
print(a1*2)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


In [66]:
# relational(>,<,==)
print(a2)
print(a2>12) #boolean

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[False  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


## vector operations

#### arithmetic

a1+a2

In [68]:
a1*a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [69]:
a1/a2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

In [70]:
a1**a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

## Array Functions

In [73]:
a1=np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[82., 63., 54.],
       [65., 84., 43.],
       [30., 31., 47.]])

In [80]:
# max, min, sum, prod
# 0->col , 1->row

print(np.max(a1))
print(np.min(a1, axis=1))

84.0
[54. 43. 30.]


In [77]:
#mean, median, std, var

np.std(a1)


18.685176008513697

In [85]:
#trigonometric functions-> sin, cosine, tan 

np.tan(a1)

array([[ 0.32982641,  0.16974975,  0.6738001 ],
       [-1.47003826, -1.07818381, -1.49838734],
       [-6.4053312 , -0.44169557, -0.12452757]])

In [86]:
# dot product

a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [87]:
# log and exponents

np.exp(a1)

array([[4.09399696e+35, 2.29378316e+27, 2.83075330e+23],
       [1.69488924e+28, 3.02507732e+36, 4.72783947e+18],
       [1.06864746e+13, 2.90488497e+13, 2.58131289e+20]])

In [88]:
# round/floor/ceil

np.ceil(np.random.random((2,3))*100)

array([[74., 80., 89.],
       [35., 69., 76.]])

## Indexing and Slicing

In [89]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [90]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
a1[0],a1[-9]

(0, 1)

In [91]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [94]:
a2[2,3]

11

In [95]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [96]:
a3[1,0,1]

5

In [97]:
#slicing
a1[2:5]

array([2, 3, 4])

In [98]:
a1[2:5:2]

array([2, 4])

In [99]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [100]:
a2[0,:]

array([0, 1, 2, 3])

In [102]:
a2[:,2]

array([ 2,  6, 10])

In [103]:
a2[1:3,1:3] # or a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [104]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [106]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [109]:
#3d  slicing
a3=np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [111]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [112]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [114]:
a3[0,1]

array([3, 4, 5])

In [116]:
a3[1,::,1]

array([10, 13, 16])

In [117]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [119]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

## Iterating

In [120]:
a1
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [121]:
a2
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [124]:
for i in np.nditer(a2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [125]:
a3
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


## Reshaping

In [126]:
# reshape

print(np.transpose(a2))

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [127]:
a2.T  #same

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [129]:
 #ravel
a3.ravel() #nd_array->1d_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

## Stacking

In [130]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [131]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## Splitting

In [132]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [133]:
# horizontal
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [135]:
# Vertical
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]