### np.sort
Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [1]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([ 3, 43, 25, 16, 46, 16, 77, 62, 31, 82, 35,  2, 14, 71, 63])

In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[ 1, 22, 53, 82],
       [15, 49, 34, 28],
       [72,  8, 14, 73],
       [40, 61, 54,  3],
       [60, 16,  3, 57],
       [94, 80, 94, 85]])

In [3]:
np.sort(a) #ascending order

array([ 2,  3, 14, 16, 16, 25, 31, 35, 43, 46, 62, 63, 71, 77, 82])

In [12]:
np.sort(a)[::-1] #descending order

array([82, 77, 71, 63, 62, 46, 43, 35, 31, 25, 16, 16, 14,  3,  2])

In [5]:
np.sort(b) 

array([[ 1, 22, 53, 82],
       [15, 28, 34, 49],
       [ 8, 14, 72, 73],
       [ 3, 40, 54, 61],
       [ 3, 16, 57, 60],
       [80, 85, 94, 94]])

In [9]:
np.sort(b, axis=0) #columnwise sorting

array([[ 1,  8,  3,  3],
       [15, 16, 14, 28],
       [40, 22, 34, 57],
       [60, 49, 53, 73],
       [72, 61, 54, 82],
       [94, 80, 94, 85]])

In [10]:
np.sort(b, axis=1) #rowwise sorting

array([[ 1, 22, 53, 82],
       [15, 28, 34, 49],
       [ 8, 14, 72, 73],
       [ 3, 40, 54, 61],
       [ 3, 16, 57, 60],
       [80, 85, 94, 94]])

### np.append
The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [13]:
# code
np.append(a,200)

array([  3,  43,  25,  16,  46,  16,  77,  62,  31,  82,  35,   2,  14,
        71,  63, 200])

In [14]:
np.append(b, np.ones((b.shape[0],1)),axis=1)

array([[ 1., 22., 53., 82.,  1.],
       [15., 49., 34., 28.,  1.],
       [72.,  8., 14., 73.,  1.],
       [40., 61., 54.,  3.,  1.],
       [60., 16.,  3., 57.,  1.],
       [94., 80., 94., 85.,  1.]])

In [15]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[ 1.        , 22.        , 53.        , 82.        ,  0.12901452],
       [15.        , 49.        , 34.        , 28.        ,  0.67833332],
       [72.        ,  8.        , 14.        , 73.        ,  0.42102015],
       [40.        , 61.        , 54.        ,  3.        ,  0.39797868],
       [60.        , 16.        ,  3.        , 57.        ,  0.36543389],
       [94.        , 80.        , 94.        , 85.        ,  0.67943111]])

### np.concatenate
numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [16]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [17]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique
With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [20]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [21]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims
With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [22]:
# code
a.shape

(15,)

In [23]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [24]:
np.expand_dims(a,axis=0)

array([[ 3, 43, 25, 16, 46, 16, 77, 62, 31, 82, 35,  2, 14, 71, 63]])

In [25]:
np.expand_dims(a,axis=1)

array([[ 3],
       [43],
       [25],
       [16],
       [46],
       [16],
       [77],
       [62],
       [31],
       [82],
       [35],
       [ 2],
       [14],
       [71],
       [63]])

### np.where
The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [26]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 6,  7,  9, 13, 14]),)

In [27]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([ 3, 43, 25, 16, 46, 16,  0,  0, 31,  0, 35,  2, 14,  0,  0])

In [28]:
np.where(a%2 == 0,0,a)

array([ 3, 43, 25,  0,  0,  0, 77,  0, 31,  0, 35,  0,  0, 71, 63])

### np.argmax
The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [29]:
# code
a

array([ 3, 43, 25, 16, 46, 16, 77, 62, 31, 82, 35,  2, 14, 71, 63])

In [30]:
np.argmax(a)

9

In [31]:
b

array([[ 1, 22, 53, 82],
       [15, 49, 34, 28],
       [72,  8, 14, 73],
       [40, 61, 54,  3],
       [60, 16,  3, 57],
       [94, 80, 94, 85]])

In [32]:
np.argmax(b,axis=0)

array([5, 5, 5, 5])

In [33]:
np.argmax(b,axis=1)

array([3, 1, 3, 1, 0, 0])

In [34]:
# np.argmin
np.argmin(a)

11

### np.cumsum
numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [35]:
a

array([ 3, 43, 25, 16, 46, 16, 77, 62, 31, 82, 35,  2, 14, 71, 63])

In [36]:
np.cumsum(a)

array([  3,  46,  71,  87, 133, 149, 226, 288, 319, 401, 436, 438, 452,
       523, 586])

In [37]:
b

array([[ 1, 22, 53, 82],
       [15, 49, 34, 28],
       [72,  8, 14, 73],
       [40, 61, 54,  3],
       [60, 16,  3, 57],
       [94, 80, 94, 85]])

In [38]:
np.cumsum(b,axis=1)

array([[  1,  23,  76, 158],
       [ 15,  64,  98, 126],
       [ 72,  80,  94, 167],
       [ 40, 101, 155, 158],
       [ 60,  76,  79, 136],
       [ 94, 174, 268, 353]])

In [39]:
np.cumsum(b)

array([   1,   23,   76,  158,  173,  222,  256,  284,  356,  364,  378,
        451,  491,  552,  606,  609,  669,  685,  688,  745,  839,  919,
       1013, 1098])

In [40]:
# np.cumprod
np.cumprod(a)

array([                   3,                  129,                 3225,
                      51600,              2373600,             37977600,
                 2924275200,         181305062400,        5620456934400,
            460877468620800,    16130711401728000,    32261422803456000,
         451659919248384000, -4825633880783839232, -8867029310029045760])

In [41]:
a

array([ 3, 43, 25, 16, 46, 16, 77, 62, 31, 82, 35,  2, 14, 71, 63])

### np.percentile
numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [42]:
a

array([ 3, 43, 25, 16, 46, 16, 77, 62, 31, 82, 35,  2, 14, 71, 63])

In [43]:
np.percentile(a,50)

35.0

In [44]:
np.median(a)

35.0

In [45]:
np.percentile(a,100)

82.0

In [46]:
np.percentile(a,10)

7.400000000000001

### np.histogram
Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [47]:
# code
a

array([ 3, 43, 25, 16, 46, 16, 77, 62, 31, 82, 35,  2, 14, 71, 63])

In [48]:
np.histogram(a,bins=[0,50,100])

(array([10,  5]), array([  0,  50, 100]))

### np.corrcoef -> correlation coefficeint
Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [49]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin
With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [50]:
# code
a

array([ 3, 43, 25, 16, 46, 16, 77, 62, 31, 82, 35,  2, 14, 71, 63])

In [51]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([], dtype=int64)

In [52]:
np.isin(a,items)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

### np.flip
The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [53]:
# code
a

array([ 3, 43, 25, 16, 46, 16, 77, 62, 31, 82, 35,  2, 14, 71, 63])

In [54]:
np.flip(a)

array([63, 71, 14,  2, 35, 82, 31, 62, 77, 16, 46, 16, 25, 43,  3])

In [55]:
b

array([[ 1, 22, 53, 82],
       [15, 49, 34, 28],
       [72,  8, 14, 73],
       [40, 61, 54,  3],
       [60, 16,  3, 57],
       [94, 80, 94, 85]])

In [56]:
np.flip(b,axis=1)

array([[82, 53, 22,  1],
       [28, 34, 49, 15],
       [73, 14,  8, 72],
       [ 3, 54, 61, 40],
       [57,  3, 16, 60],
       [85, 94, 80, 94]])

### np.put
The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [57]:
# code
a

array([ 3, 43, 25, 16, 46, 16, 77, 62, 31, 82, 35,  2, 14, 71, 63])

In [58]:
np.put(a,[0,1],[110,530])

In [59]:
a

array([110, 530,  25,  16,  46,  16,  77,  62,  31,  82,  35,   2,  14,
        71,  63])

### np.delete
The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [60]:
# code
a

array([110, 530,  25,  16,  46,  16,  77,  62,  31,  82,  35,   2,  14,
        71,  63])

In [61]:
np.delete(a,[0,2,4])

array([530,  16,  16,  77,  62,  31,  82,  35,   2,  14,  71,  63])

In [62]:
np.delete(a,0)

array([530,  25,  16,  46,  16,  77,  62,  31,  82,  35,   2,  14,  71,
        63])

## Set functions
>np.union1d

>np.intersect1d

>np.setdiff1d

>np.setxor1d

>np.in1d

In [63]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [64]:
np.intersect1d(m,n)

array([3, 4, 5])

In [65]:
np.setdiff1d(n,m)

array([6, 7])

In [66]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [68]:
np.in1d(m,1)

array([ True, False, False, False, False])

In [69]:
m[np.in1d(m,1)]

array([1])

### np.clip
numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [71]:
# code
a

array([110, 530,  25,  16,  46,  16,  77,  62,  31,  82,  35,   2,  14,
        71,  63])

In [70]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 25, 25, 46, 25, 75, 62, 31, 75, 35, 25, 25, 71, 63])